-- Populate word_pairs table with all existing word pairs
INSERT INTO public.word_pairs (crewmate_word, impostor_word, category) VALUES
  -- Água/Mar (20 pares)
  ('OCEANO', 'TUBARÃO', 'agua'),
  ('MAR', 'PEIXE', 'agua'),
  ('ÁGUA', 'GELO', 'agua'),
  ('PRAIA', 'CONCHA', 'agua'),
  ('ONDA', 'SURFISTA', 'agua'),
  ('RIO', 'PONTE', 'agua'),
  ('LAGO', 'CISNE', 'agua'),
  ('PISCINA', 'NADADOR', 'agua'),
  ('CHUVA', 'GUARDA-CHUVA', 'agua'),
  ('GOTA', 'NUVEM', 'agua'),
  ('CACHOEIRA', 'PEDRA', 'agua'),
  ('ILHA', 'COCO', 'agua'),
  ('PORTO', 'BARCO', 'agua'),
  ('FAROL', 'NAVIO', 'agua'),
  ('ANZOL', 'PESCADOR', 'agua'),
  ('REDE', 'PESCARIA', 'agua'),
  ('CORAL', 'MERMAID', 'agua'),
  ('SAL', 'ÁGUA', 'agua'),
  ('ESPUMA', 'MAR', 'agua'),
  ('MOLUSCO', 'CONCHA', 'agua'),
  
  -- Veículos/Transporte (20 pares)
  ('CARRO', 'RODA', 'veiculos'),
  ('BICICLETA', 'PEDAL', 'veiculos'),
  ('AVIÃO', 'ASA', 'veiculos'),
  ('BARCO', 'VELA', 'veiculos'),
  ('MOTO', 'CAPACETE', 'veiculos'),
  ('ÔNIBUS', 'PARADA', 'veiculos'),
  ('TREM', 'TRILHO', 'veiculos'),
  ('METRÔ', 'ESTAÇÃO', 'veiculos'),
  ('TAXI', 'TAXÍMETRO', 'veiculos'),
  ('HELICÓPTERO', 'HÉLICE', 'veiculos'),
  ('NAVIO', 'ÂNCORA', 'veiculos'),
  ('SUBWAY', 'TÚNEL', 'veiculos'),
  ('PATINETE', 'MANOBRA', 'veiculos'),
  ('SKATE', 'RODA', 'veiculos'),
  ('CARRINHO', 'BRINQUEDO', 'veiculos'),
  ('AMBULÂNCIA', 'SIRENE', 'veiculos'),
  ('BOMBEIRO', 'CARRETEL', 'veiculos'),
  ('GUINCHO', 'CARRO', 'veiculos'),
  ('GARAGEM', 'VEÍCULO', 'veiculos'),
  ('ESTACIONAMENTO', 'VAGA', 'veiculos'),
  
  -- Casa/Construção (20 pares)
  ('CASA', 'PORTA', 'casa'),
  ('ESCOLA', 'QUADRO', 'casa'),
  ('HOSPITAL', 'MÉDICO', 'casa'),
  ('COZINHA', 'FOGÃO', 'casa'),
  ('QUARTO', 'CAMA', 'casa'),
  ('SALA', 'SOFÁ', 'casa'),
  ('BANHEIRO', 'CHUVEIRO', 'casa'),
  ('JANELA', 'VIDRO', 'casa'),
  ('TELHADO', 'TELHA', 'casa'),
  ('PAREDE', 'TINTA', 'casa'),
  ('CHÃO', 'PISO', 'casa'),
  ('TETO', 'LÂMPADA', 'casa'),
  ('CORREDOR', 'PORTA', 'casa'),
  ('ESCADA', 'DEGRAU', 'casa'),
  ('ELEVADOR', 'BOTÃO', 'casa'),
  ('APARTAMENTO', 'ANDAR', 'casa'),
  ('PRÉDIO', 'ELEVADOR', 'casa'),
  ('CONSTRUÇÃO', 'CIMENTO', 'casa'),
  ('OBRA', 'PEDREIRO', 'casa'),
  ('FUNDAÇÃO', 'CASA', 'casa'),
  
  -- Animais (20 pares)
  ('CACHORRO', 'OSSO', 'animais'),
  ('GATO', 'RATO', 'animais'),
  ('ELEFANTE', 'TROMBA', 'animais'),
  ('LEÃO', 'JUBAL', 'animais'),
  ('TIGRE', 'LISTRA', 'animais'),
  ('URSO', 'MEL', 'animais'),
  ('MACACO', 'BANANA', 'animais'),
  ('COELHO', 'CENOURA', 'animais'),
  ('CAVALO', 'FERRO', 'animais'),
  ('VACA', 'LEITE', 'animais'),
  ('PORCO', 'CHIQUEIRO', 'animais'),
  ('GALINHA', 'OVO', 'animais'),
  ('PATO', 'LAGO', 'animais'),
  ('PÁSSARO', 'NINHO', 'animais'),
  ('ÁGUIA', 'GARRA', 'animais'),
  ('COBRA', 'VENENO', 'animais'),
  ('TARTARUGA', 'CASCO', 'animais'),
  ('GIRAFA', 'PESCOÇO', 'animais'),
  ('ZEBRA', 'LISTRA', 'animais'),
  ('RINOCERONTE', 'CHIFRE', 'animais'),
  
  -- Natureza (20 pares)
  ('ÁRVORE', 'FOLHA', 'natureza'),
  ('FLOR', 'PÉTALA', 'natureza'),
  ('MONTANHA', 'NEVE', 'natureza'),
  ('FLORESTA', 'ANIMAL', 'natureza'),
  ('CAMPO', 'GRAMA', 'natureza'),
  ('DESERTO', 'CACTUS', 'natureza'),
  ('VULCÃO', 'LAVA', 'natureza'),
  ('TERREMOTO', 'TREMOR', 'natureza'),
  ('RAIO', 'TROVÃO', 'natureza'),
  ('ARCO-ÍRIS', 'CHUVA', 'natureza'),
  ('VENTO', 'BANDEIRA', 'natureza'),
  ('FUMAÇA', 'FOGO', 'natureza'),
  ('SEMENTE', 'PLANTA', 'natureza'),
  ('RAIZ', 'TERRA', 'natureza'),
  ('TRONCO', 'ÁRVORE', 'natureza'),
  ('GALHO', 'FOLHA', 'natureza'),
  ('FRUTO', 'SEMENTE', 'natureza'),
  ('ESPINHO', 'ROSA', 'natureza'),
  ('CIPÓ', 'ÁRVORE', 'natureza'),
  ('MUSGO', 'PEDRA', 'natureza'),
  
  -- Tecnologia (20 pares)
  ('COMPUTADOR', 'TECLADO', 'tecnologia'),
  ('CELULAR', 'TELA', 'tecnologia'),
  ('INTERNET', 'WI-FI', 'tecnologia'),
  ('TABLET', 'TOQUE', 'tecnologia'),
  ('NOTEBOOK', 'MOUSE', 'tecnologia'),
  ('SMARTPHONE', 'APLICATIVO', 'tecnologia'),
  ('CÂMERA', 'LENTE', 'tecnologia'),
  ('TELEVISÃO', 'CONTROLE', 'tecnologia'),
  ('RÁDIO', 'ANTENA', 'tecnologia'),
  ('FONE', 'CABO', 'tecnologia'),
  ('ALTO-FALANTE', 'SOM', 'tecnologia'),
  ('MICROFONE', 'VOZ', 'tecnologia'),
  ('IMPRESSORA', 'PAPEL', 'tecnologia'),
  ('SCANNER', 'DOCUMENTO', 'tecnologia'),
  ('ROTEADOR', 'SINAL', 'tecnologia'),
  ('BATERIA', 'CARREGADOR', 'tecnologia'),
  ('PENDRIVE', 'ARQUIVO', 'tecnologia'),
  ('WEBCAM', 'VÍDEO', 'tecnologia'),
  ('DRONE', 'HÉLICE', 'tecnologia'),
  ('ROBÔ', 'PROGRAMA', 'tecnologia'),
  
  -- Corpo Humano (20 pares)
  ('CABEÇA', 'CABELO', 'corpo'),
  ('MÃO', 'DEDO', 'corpo'),
  ('OLHO', 'PUPILA', 'corpo'),
  ('OUVIDO', 'ORELHA', 'corpo'),
  ('NARIZ', 'NARINA', 'corpo'),
  ('BOCA', 'DENTE', 'corpo'),
  ('LÍNGUA', 'PALADAR', 'corpo'),
  ('PESCOÇO', 'GARGANTA', 'corpo'),
  ('PEITO', 'CORAÇÃO', 'corpo'),
  ('BRAÇO', 'COTOVELO', 'corpo'),
  ('PERNA', 'JOELHO', 'corpo'),
  ('PÉ', 'DEDO', 'corpo'),
  ('UNHA', 'DEDO', 'corpo'),
  ('PELE', 'PORO', 'corpo'),
  ('OSSO', 'ESQUELETO', 'corpo'),
  ('MÚSCULO', 'FORÇA', 'corpo'),
  ('SANGUE', 'VEIA', 'corpo'),
  ('CÉREBRO', 'NEURÔNIO', 'corpo'),
  ('PULMÃO', 'AR', 'corpo'),
  ('RIM', 'FILTRO', 'corpo'),
  
  -- Comida (20 pares)
  ('BANANA', 'CASCA', 'comida'),
  ('PÃO', 'FARINHA', 'comida'),
  ('SORVETE', 'CASQUINHA', 'comida'),
  ('PIZZA', 'FATIA', 'comida'),
  ('HAMBÚRGUER', 'PÃO', 'comida'),
  ('BOLO', 'VELA', 'comida'),
  ('SALADA', 'ALFACE', 'comida'),
  ('SOPA', 'COLHER', 'comida'),
  ('ARROZ', 'GRÃO', 'comida'),
  ('FEIJÃO', 'GRAVINHA', 'comida'),
  ('MACARRÃO', 'MOLHO', 'comida'),
  ('CARNE', 'GRELHA', 'comida'),
  ('PEIXE', 'ESPINHA', 'comida'),
  ('OVO', 'CASCA', 'comida'),
  ('LEITE', 'COPO', 'comida'),
  ('CAFÉ', 'XÍCARA', 'comida'),
  ('AÇÚCAR', 'DOCE', 'comida'),
  ('SAL', 'TEMPERO', 'comida'),
  ('CHOCOLATE', 'BARRA', 'comida'),
  ('BISCOITO', 'PACOTE', 'comida'),
  
  -- Espaço (20 pares)
  ('SOL', 'LUZ', 'espaco'),
  ('ESTRELA', 'CONSTELAÇÃO', 'espaco'),
  ('LUA', 'CRATERA', 'espaco'),
  ('PLANETA', 'ÓRBITA', 'espaco'),
  ('ASTEROIDE', 'ROCHA', 'espaco'),
  ('COMETA', 'CAUDA', 'espaco'),
  ('GALÁXIA', 'ESTRELA', 'espaco'),
  ('NEBULOSA', 'GÁS', 'espaco'),
  ('BURACO NEGRO', 'GRAVIDADE', 'espaco'),
  ('ASTRONAUTA', 'FOGUETE', 'espaco'),
  ('SATÉLITE', 'ÓRBITA', 'espaco'),
  ('TELESCÓPIO', 'LENTE', 'espaco'),
  ('ESTAÇÃO ESPACIAL', 'ASTRONAUTA', 'espaco'),
  ('MARTE', 'ROVER', 'espaco'),
  ('JÚPITER', 'LUA', 'espaco'),
  ('SATURNO', 'ANEL', 'espaco'),
  ('URANO', 'GÁS', 'espaco'),
  ('NEPTUNO', 'AZUL', 'espaco'),
  ('MERCÚRIO', 'QUENTE', 'espaco'),
  ('VÊNUS', 'NUVEM', 'espaco'),
  
  -- Livros/Educação (20 pares)
  ('LIVRO', 'PÁGINA', 'livros'),
  ('CANETA', 'TINTA', 'livros'),
  ('CADERNO', 'LINHA', 'livros'),
  ('LÁPIS', 'GRAFITE', 'livros'),
  ('BORRACHA', 'LÁPIS', 'livros'),
  ('RÉGUA', 'MEDIDA', 'livros'),
  ('ESTOJO', 'MATERIAL', 'livros'),
  ('MOCHILA', 'CADERNO', 'livros'),
  ('PROFESSOR', 'QUADRO', 'livros'),
  ('ALUNO', 'CADEIRA', 'livros'),
  ('AULA', 'SALA', 'livros'),
  ('PROVA', 'PERGUNTA', 'livros'),
  ('DICIONÁRIO', 'PALAVRA', 'livros'),
  ('ENCICLOPÉDIA', 'INFORMAÇÃO', 'livros'),
  ('BIBLIOTECA', 'LIVRO', 'livros'),
  ('REVISTA', 'ARTIGO', 'livros'),
  ('JORNAL', 'NOTÍCIA', 'livros'),
  ('FOLHA', 'PAPEL', 'livros'),
  ('CARTOLINA', 'COR', 'livros'),
  ('GIZ', 'QUADRO', 'livros'),
  
  -- Música (20 pares)
  ('MÚSICA', 'NOTA', 'musica'),
  ('VIOLÃO', 'CORDA', 'musica'),
  ('BATERIA', 'BAQUETA', 'musica'),
  ('PIANO', 'TECLA', 'musica'),
  ('GUITARRA', 'PALHETA', 'musica'),
  ('FLAUTA', 'BUraco', 'musica'),
  ('SAXOFONE', 'BOCAL', 'musica'),
  ('TROMPETE', 'BOCAL', 'musica'),
  ('VIOLINO', 'ARCO', 'musica'),
  ('TAMBOR', 'BAQUETA', 'musica'),
  ('MICROFONE', 'CANTOR', 'musica'),
  ('ALTO-FALANTE', 'SOM', 'musica'),
  ('FONE DE OUVIDO', 'MÚSICA', 'musica'),
  ('RÁDIO', 'ESTAÇÃO', 'musica'),
  ('CD', 'MÚSICA', 'musica'),
  ('VINIL', 'AGULHA', 'musica'),
  ('PLAYLIST', 'MÚSICA', 'musica'),
  ('CANÇÃO', 'LETRA', 'musica'),
  ('CORO', 'VOZ', 'musica'),
  ('ORQUESTRA', 'MAESTRO', 'musica'),
  
  -- Esportes (20 pares)
  ('FUTEBOL', 'BOLA', 'esportes'),
  ('NATAÇÃO', 'PISCINA', 'esportes'),
  ('CORRIDA', 'TÊNIS', 'esportes'),
  ('BASQUETE', 'CESTA', 'esportes'),
  ('VOLEI', 'REDE', 'esportes'),
  ('TÊNIS', 'RAQUETE', 'esportes'),
  ('GOLFE', 'TACO', 'esportes'),
  ('CICLISMO', 'BICICLETA', 'esportes'),
  ('BOX', 'LUVA', 'esportes'),
  ('LUTA', 'RINGUE', 'esportes'),
  ('SURFE', 'PRANCHA', 'esportes'),
  ('SKATE', 'MANOBRA', 'esportes'),
  ('ESQUI', 'NEVE', 'esportes'),
  ('PATINS', 'RODA', 'esportes'),
  ('ARCO E FLECHA', 'ALVO', 'esportes'),
  ('TIRO', 'ALVO', 'esportes'),
  ('ATLETISMO', 'PISTA', 'esportes'),
  ('GINÁSTICA', 'APARELHO', 'esportes'),
  ('DANÇA', 'PASSO', 'esportes'),
  ('IÔ-IÔ', 'CORDÃO', 'esportes')
ON CONFLICT DO NOTHING;


